<a href="https://colab.research.google.com/github/HA19172/CE888/blob/master/LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##ANSWERS

In [0]:
#commit1

#1)

In [0]:
import numpy.random
n==np.random.randint(100, size=(4,2))
print(n)
print(n.size)
print(n.shape)
print(n.ndim) 

[[[6 1 2 7]]

 [[6 7 8 2]]]
8
(2, 1, 4)
3


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


#2)

In [0]:
m=np.random.randint(1,100,10)
print(m)
sorted=np.sort(m)
print("sorted:",sorted)
reversed=np.sort(m)[::-1]
print("reversed:",reversed)


[63 25 88 52  4 78 84 28 27 96]
sorted: [ 4 25 27 28 52 63 78 84 88 96]
reversed: [96 88 84 78 63 52 28 27 25  4]


#3)

In [0]:
a=np.arange(1,10)
print(a)
a.reshape(3,3)

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#4)

In [0]:
a=np.random.randint(100, size=(2,2))
b=np.random.randint(100, size=(2,2))
c=np.stack((a,b))
d=np.stack((a,b),axis=1)
print(c)
print(d)

[[[19 99]
  [11 20]]

 [[95 82]
  [78 29]]]
[[[19 99]
  [95 82]]

 [[11 20]
  [78 29]]]


#5)

In [0]:
a=np.random.randint(1,10,4)
b=np.random.randint(1,10,4)
print(a)
print(b)
c=list()
for i in a:
  for j in b:
    if i==j:
       c.append(i)
print(c)

[6 5 5 1]
[6 7 3 4]
[6]


#6)

In [0]:
p=np.random.randint(100, size=(5,5))
print(p)
each_column_max=np.max(p, axis=0)
print("each_column_max=",each_column_max)
each_column_min=np.min(p, axis=0)
print("each_column_min=",each_column_min)

each_row_max=np.max(p, axis=1)
print("each_row_max=",each_row_max)
each_row_min=np.min(p, axis=1)
print("each_row_min=",each_row_min)


[[ 2 29 26 62 82]
 [52 43 64 21 20]
 [37 45 39 66 41]
 [15  8 63 73 10]
 [94 84 80 14 93]]
each_column_max= [94 84 80 73 93]
each_column_min= [ 2  8 26 14 10]
each_row_max= [82 64 66 73 94]
each_row_min= [ 2 20 37  8 14]


#7)

In [0]:
t=np.random.randint(1000, size=100)
print(t)
print(np.mean(t))
print(np.median(t))
print(np.std(t))

[857 731 867 569 158 160 440 277 929 783  40 457  65 344  69 826 131 385
 824 976 654  37 212 386 725 670 536 867 206 611 963   0 839 244 718  75
 979 368 393 171 521 461 942 393  62 303 286 968 169 561 601 779 276 920
 713 489 830 666 231  19 237 938 309 640 682 168 790 277 973  87 865 574
 137 258 506 703 659 757 205 598  36 835 554 464 998 567 242 149 396 299
 466 975  24 304 593  95 398 904 772 317]
494.83
477.5
298.17424620513424


#8)


In [0]:
from sklearn.preprocessing import normalize
new=np.random.randint(100, size=(5,5))
print(new)
np.linalg.norm(new)

[[ 9 47 91 50 74]
 [19 25 95  0 55]
 [28 70 72 57 36]
 [ 1 25 36 62 31]
 [26 63 58 29 22]]


251.11152900653525

#9)

In [0]:
a=np.ones((4,4,3))
b=np.ones((4,4))
c=np.dot(b,a)
print(c)



[[[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]]
